
// Package types contains functions that return a resource or property type when called.
// This code is autogenerated. 
// Do not edit it by hand.
package types
import "github.com/awslabs/aws-cloudformation-template-builder/spec/cf"

 
func PolicyProperty() cf.PropertyType {
    return cf.PropertyType{Documentation:"", Properties:map[string]cf.Property{"Version":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"", PrimitiveType:"String", Required:false, Type:"", UpdateType:""}, "Id":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"", PrimitiveType:"String", Required:false, Type:"", UpdateType:""}, "Statement":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"Statement", PrimitiveItemType:"", PrimitiveType:"", Required:false, Type:"List", UpdateType:""}}}
}


