
// Package types contains functions that return a resource or property type when called.
// This code is autogenerated. 
// Do not edit it by hand.
package types
import "github.com/awslabs/aws-cloudformation-template-builder/spec/cf"

 
func StatementProperty() cf.PropertyType {
    return cf.PropertyType{Documentation:"", Properties:map[string]cf.Property{"Resource":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"String", PrimitiveType:"", Required:false, Type:"List", UpdateType:""}, "Effect":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"", PrimitiveType:"String", Required:false, Type:"", UpdateType:""}, "NotAction":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"String", PrimitiveType:"", Required:false, Type:"List", UpdateType:""}, "NotPrincipal":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"String", PrimitiveType:"", Required:false, Type:"Map", UpdateType:""}, "Action":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"String", PrimitiveType:"", Required:false, Type:"List", UpdateType:""}, "NotResource":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"String", PrimitiveType:"", Required:false, Type:"List", UpdateType:""}, "Condition":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"Json", PrimitiveType:"", Required:false, Type:"Map", UpdateType:""}, "Sid":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"", PrimitiveType:"String", Required:false, Type:"", UpdateType:""}, "Principal":cf.Property{Documentation:"", DuplicatesAllowed:false, ItemType:"", PrimitiveItemType:"String", PrimitiveType:"", Required:false, Type:"Map", UpdateType:""}}}
}


