package builder

import "codecommit/builders/cfn-skeleton/spec"

type CfnBuilder struct {
	Builder
}

func NewCfnBuilder(includeOptional, buildIamPolicies bool) CfnBuilder {
	var b CfnBuilder
	b.Spec = spec.Cfn
	b.IncludeOptionalProperties = includeOptional
	b.BuildIamPolicies = buildIamPolicies

	return b
}

func (b CfnBuilder) Template(config map[string]string) (map[string]interface{}, map[interface{}]interface{}) {
	// Generate resources
	resources := make(map[string]interface{})
	comments := make(map[string]interface{})
	for name, resourceType := range config {
		resources[name], comments[name] = b.newResource(resourceType)
	}

	// Build the template
	return map[string]interface{}{
			"AWSTemplateFormatVersion": "2010-09-09",
			"Resources":                resources,
			// TODO: "Outputs": outputs,
		}, map[interface{}]interface{}{
			"":          "Template generated by cfn-build",
			"Resources": comments,
		}
}
