package builder

import "codecommit/builders/cfn-spec-go/spec"

type CfnBuilder struct {
	Builder
}

func NewCfnBuilder(includeOptional bool) CfnBuilder {
	var b CfnBuilder
	b.Spec = spec.Cfn
	b.IncludeOptionalProperties = includeOptional

	return b
}

func (b CfnBuilder) Template(config map[string]string) map[string]interface{} {
	// Generate resources
	resources := make(map[string]interface{})
	for name, resourceType := range config {
		resources[name] = b.newResource(resourceType)
	}

	// Build the template
	return map[string]interface{}{
		"AWSTemplateFormatVersion": "2010-09-09",
		"Description":              "Template generated by cfn-build",
		"Resources":                resources,
		// TODO: "Outputs": outputs,
	}
}
